server:
  port: 9090
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/vue-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # 搜索指定包别名，用于扫描domain如果换位置就写指定的位置，如果不换位置其他位置也有domain需要扫描的，就在后面加，号。下面同理
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml # mapper映射文件位置
  type-aliases-package: com.xuan.entity # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 日志配置
logging:
  # 日志级别
  level:
    root: info
